# Generated by Django 3.1.4 on 2020-12-08 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_name', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('how_many_people', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('add_note', models.TextField(blank=True, max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
