# Generated by Django 3.1.4 on 2020-12-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepost',
            name='date',
        ),
    ]
