# Generated by Django 3.1.4 on 2020-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_note',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='food_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
