# Generated by Django 3.1.4 on 2020-12-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_post', '0002_auto_20201211_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
