# Generated by Django 3.1.4 on 2020-12-10 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donate_post', '0003_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
