# Generated by Django 3.1.4 on 2020-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_post', '0005_auto_20201211_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('D', 'Want to donate'), ('R', 'Request for donate')], default='D', max_length=20),
            preserve_default=False,
        ),
    ]
