# Generated by Django 3.1.4 on 2020-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_post', '0006_post_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
